<?php
$v->layout('main', ['title' => 'peliculas - Ficha']);
echo "<b>Título: </b>" . $pelicula['titulo'] . "<br />";
echo "<b>Año: </b>" . $pelicula['anyo'] . "<br />";
echo "<b>Duracion: </b>" . $pelicula['duracion'] . "<br />";
echo "<b>Directores:<br />";

foreach ($peliDirector as $variable) {
   
    echo '<a href="'.$_ENV['APP_URL'].'/director/' . $variable['id'] . '" class="custom-card">';
    echo $variable['nombre'] . "<br>";
    echo '</a>';
}
echo "<b>Actores:<br />";
foreach ($peliActor as $variable) {
    
    echo '<a href="'.$_ENV['APP_URL'].'/actor/' . $variable['id'] . '" class="custom-card">';
    echo $variable['nombre'] ."<br>";
    echo '</a>';
}
echo "<b>Criticas: <br />";
var_dump($criticas);
foreach ($criticas as $critica) {
    

}
?>